<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <BaseOutputPath>D:\Dev\MaterialSimulator</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignInXamlToolkitAddOns" Version="0.0.63" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Simulator.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
